### PR TITLE
Integration test improvements

### PR DESCRIPTION
**Pull request by martinheidegger**
When trying to fix the tests for #450 I noticed some problems with how the test system is setup. In order to not bloat #450 let me push here a separate PR.

### CODE REVIEW

**Comment by martinheidegger** [comment]
(re)Based on #456 and while I tried to get appveyor to work, but it seems like its a deeper-rooted issue _(with dat or nodejs)_ that I couldn't get fixed. 

ref. https://github.com/nodejs/help/issues/1083 and https://github.com/nodejs/node/issues/18391

**Comment by juliangruber** [comment]
Wow, rough :|

**Comment by martinheidegger** [comment]
I think it's still worth merging as is

**Comment by juliangruber** [comment]
gotcha! can you look at the conflicts? then +1 to merging

**Comment by martinheidegger** [comment]
rebased on master, not sure what the problem might have been?!

**Comment by juliangruber** [comment]
Awesome, thank you!

**Comment by martinheidegger** [comment]
Would it be possible to merge this branch with a merge commit? To keep the commit log?

**Comment by juliangruber** [comment]
doesn't it still have the commit log in the description? https://github.com/datproject/dat-desktop/commit/d8ef48a54b4782278fd66fc178c24ce2b493bde4

Or do you want to see more in the history, then I'm ok with that too :)

**Comment by martinheidegger** [comment]
I asked for it in order to be able to blame. I understand the current way and I am on the fence about which one is better

**Comment by martinheidegger** [comment]
Have thought about this a little more _(shoulda done that before commenting)_. The current statement is fine. I will keep the branch alive in order someone wants to reference it.

**Comment by juliangruber** [comment]
Ah, I see what you're saying! Yeah I think just using git a merge commit would have been better, but with the extra information GitHub provides this gives a good balance between brevity and inspectability

**Comment by martinheidegger** [comment]
Smaller commits in future 😄

**Pull request merged**
