### PR TITLE
[WIP] Add download screen

### PR DESCRIPTION
**Pull request by juliangruber**
This is a WIP pull request for https://github.com/datproject/dat-desktop/issues/290.

It currently looks like this:

screen shot 2017-05-16 at 15 09 36

There is currently a bug where you sometimes see a blank view (the placeholder gets rendered), I'm hoping to fix this @yoshuawuyts later this week.

### CODE REVIEW

**Comment by Kriesse** [comment]
@juliangruber Can't start styling, because:
image

**Comment by juliangruber** [comment]
@Kriesse should be fixed!

**Comment by juliangruber** [comment]
this looks so sweet!

**Comment by Kriesse** [comment]
@juliangruber what's still missing here?

**Pull request merged**
