### PR TITLE
appease the ci gods

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Dep CI isn't happy, even if semver kicks in. This should fix it. Thanks!

### CODE REVIEW

**Comment by juliangruber** [comment]
choo-expose and nanologger are unlicensed, that's why it complains it seems

**Comment by yoshuawuyts** [comment]
Yeah so I fixed that but apparently it doesn't pick up the semver patch
change :(

**Comment by juliangruber** [comment]
you can re-run the dependency-ci builds through the web ui, i just triggered that so it should be fine soon

**Comment by yoshuawuyts** [comment]
hmm, apparently it's still not working. I think we ought to just disable dependency-ci then :/

screen shot 2017-04-21 at 13 14 00

**Comment by yoshuawuyts** [comment]
blep, just disabled dep ci - can't get it to pass so if it's gonna get stuck on a false positive I don't think it's worth having around

**Comment by juliangruber** [comment]
yeah, dependency-ci seems to be behind!

**Pull request closed without merging**
