### PR TITLE
Fix deleting error dats. Closes #400.

### LINKED ISSUE #400: can't delete error dats

### PR DESCRIPTION
**Pull request by juliangruber**
this currently looks like this so I think it needs more styling:

screen shot 2017-05-29 at 14 58 28

### CODE REVIEW

**Comment by Kriesse** [comment]
@juliangruber Agreed, styling is not 100% yet. I can't reproduce this locally to view it, any tips?

**Comment by juliangruber** [comment]
1) make folders `~/Desktop/foo` and `~/Desktop/foo/bar`
2) share `~/Desktop/foo/bar` in Dat Desktop
3) close Dat Desktop
4) remove `~/Desktop/foo`
5) open Dat Desktop

This way it should always show an error :)

**Comment by Kriesse** [comment]
@juliangruber Yay, thank you! That worked :D 
Looks like this now, I'd like to call it done and merge. 

image

**Comment by yoshuawuyts** [comment]
Looks like tests are failing tho https://travis-ci.org/datproject/dat-desktop/jobs/237234304

**Comment by juliangruber** [comment]
this is working locally, tests are flacky it seems. i'll add some timeouts before the clipboard stuff.

**Pull request merged**
