### PR TITLE
[WIP] add inspect screen. closes #385

### LINKED ISSUE #385: also open detail view when clicking on a dat

### PR DESCRIPTION
**Pull request by juliangruber**
this currently doesn't work really because of some dom diffing problems

### CODE REVIEW

**Comment by Kriesse** [comment]
@juliangruber When I edit the name of a dat and click "Save", it navigates to the detail view (and does not save)

**Comment by juliangruber** [comment]
@Kriesse this should be fixed now :)

**Comment by Kriesse** [comment]
@juliangruber What are the reasons for the failing tests? Otherwise, looks merge-ready to me!

**Comment by juliangruber** [comment]
only one part of the CI setup failed, and it can't be rerun for some reason. Merging!

**Pull request merged**
