### PR TITLE
fix open folder problem on linux in the dist version

### LINKED ISSUE #273: Bug: Open folder on linux
I'm testing the latest version (5726a8ec7a3f35a83c48ed787d40b577cc968f32).
There is a problem on linux when i try to open the dats folder by clicking on the folder-icon.

It looks like the xdg-open script can not be executed in the electron context. I have no idea at the moment, because it works i the development build.

image

_Also the Styles (overflow) of the error-popup should be maybe improved :wink:_

### PR DESCRIPTION
**Pull request by mojoaxel**
fixes #273 

Works on linux.
Should be tested on Mac (and windows) before merging, but I don't expect problems!

### CODE REVIEW

**Comment by mojoaxel** [comment]
By the way..I have no idea, why the travis build is broken! I didn't have problems.

**Comment by yoshuawuyts** [comment]
Merged in 744b244 - thanks heaps for the fix! :grin:

**Comment by yoshuawuyts** [comment]
(also reference to the API docs: https://github.com/electron/electron/blob/master/docs/api/shell.md)

**Comment by juliangruber** [comment]
I'm working on the travis builds, it looks like an issue with prebuild

**Pull request closed without merging**
