### PR TITLE
Add dat-doctor

### PR DESCRIPTION
**Pull request by juliangruber**
For #125.

@yoshuawuyts do you want to take this over and decide how to render in the UI? Also we might want to add a key input somewhere so you can run `doctor({ id: id })` when someone else sends you a doctor link.

### CODE REVIEW

**Comment by karissa** [comment]
@Kriesse and I had an idea (for later, perhaps) that when you click on a dat you get a info view that might have a 'doctor'/'advanced' section for viewing more debugging style stuff

**Comment by juliangruber** [comment]
great idea! So maybe have a debug pane hidden in the help menu and one per dat would work

**Comment by juliangruber** [comment]
let's not merge this though until it becomes functional, otherwise the code would just be confusing

**Comment by maxogden** [comment]
if you wanna render a terminal looking thing for debug output: https://gist.github.com/maxogden/5953535

**Comment by juliangruber** [comment]
@yoshuawuyts this prints output in the devtools for now. shall we merge?

**Comment by yoshuawuyts** [comment]
yeah sounds good to me (:

**Pull request merged**
