### PR TITLE
Add warning on duplicate dat. Closes #245

### LINKED ISSUE #245: Warn on duplicate Dat
When already imported Dat. This Dat has already been imported. You can find it in your list of Dats

### PR DESCRIPTION
**Pull request by juliangruber**
@yoshuawuyts this should work afaik, but doesn't yet. Somehow `err.warn = true` isn't preserved until it reaches `models/error.js`. This looks like an issue in choo, right?

### CODE REVIEW

**Comment by karissa** [comment]
I get the correct error message, but I hit the 'OK' button and it doesn't dismiss.

**Comment by juliangruber** [comment]
> I get the correct error message, but I hit the 'OK' button and it doesn't dismiss.

I've noticed this too in another place, will investigate

**Comment by juliangruber** [comment]
> I get the correct error message, but I hit the 'OK' button and it doesn't dismiss.

this is fixed now. @yoshuawuyts mind to give a little quick review on the last commit?

**Comment by juliangruber** [comment]
@yoshuawuyts also, can you please comment on this?

> @yoshuawuyts this should work afaik, but doesn't yet. Somehow err.warn = true isn't preserved until it reaches models/error.js. This looks like an issue in choo, right?

**Comment by yoshuawuyts** [comment]
Creating duplicate dats still crashes on my machine. I hit the `create new dat` button twice in a row on the same directory

screen shot 2017-03-20 at 13 14 27

**Pull request closed without merging**
