### PR TITLE
remove choo-model

### PR DESCRIPTION
**Pull request by yoshuawuyts**
realized `choo-model` is not ideal hah; just moving some code around (:

### CODE REVIEW

**Comment by juliangruber** [comment]
to me this looks cleaner with choo-model, what's the issue with it?

**Comment by karissa** [comment]
love all the work you're putting into making the codebase stable and awesome! I'm down to merge this, but in general I always wonder if we're refactoring things prematurely -- i want to make sure we can roll out the desktop app with all the goodies before it's all old news!! :)

**Comment by karissa** [comment]
(and we're ALL guilty of this!!)

**Comment by yoshuawuyts** [comment]
@juliangruber got seriously frustrated the other day when refactoring all the `modal` stuff and trying to figure out which events were available. Thought `choo-model` was going to help with readability but instead it's been doing the exact opposite for me. By not using `choo-model` we got a manifest of available methods available on the model which is useful when you're trying to use the API. Also makes it easier to spot when our API is complicated or weirdly named so we can later go in and change it.

@karissa took me 10 mins to whip this out, I generally agree with you but figured this might be a quick easy win (:

**Comment by karissa** [comment]
Cool beans!

**Comment by juliangruber** [comment]
@yoshuawuyts ok +1 then, if we want we can think about a better abstraction later then

**Pull request merged**
