### PR TITLE
SLEEP

### PR DESCRIPTION
**Pull request by juliangruber**
This is a pull request for updating Dat Desktop to the SLEEP format. The original issue is https://github.com/datproject/dat-desktop/issues/323.

TODO

- [x] account for `dat.stats` not always being present
- [x] test performance without dat-worker
- [x] ensure all events fire
- [ ] add easy way to reset archive in case of incompatible `.dat` folder from previous hyper* version
- [ ] ..what else?

### CODE REVIEW

**Comment by juliangruber** [comment]
and the dat in question is dat://79cf7ecc9baf627642099542b3714bbef51810da9f541eabb761029969d0161b

**Comment by juliangruber** [comment]
currently need `.bytesProgress` /cc @mafintosh

**Comment by juliangruber** [comment]
after upgrading dat-node to the new hyper stack, something seems off:

https://www.youtube.com/watch?v=5F0plfGNPQY

This _does_ work with dat-next and dat-next, but not dat-node and dat-next.

**Comment by juliangruber** [comment]
screen shot 2017-05-05 at 08 40 56

**Comment by juliangruber** [comment]
screen shot 2017-05-05 at 08 56 39

**Comment by juliangruber** [comment]
the root error message seem to be `Replication error: Remote signature could not be verified`

**Comment by joehand** [comment]
> the root error message seem to be Replication error: Remote signature could not be verified

Solved via hyperdrive update (according to @juliangruber on irc)

**Comment by juliangruber** [comment]
true, sorry forgot to post here! thanks again :)

**Comment by juliangruber** [comment]
DEMO TIME https://www.youtube.com/watch?v=QSTMJ3Hg4rU

**Comment by juliangruber** [comment]
and connection issues:

screen shot 2017-05-08 at 11 23 28

**Pull request merged**
