### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by juliangruber**
This is a WIP pull request, let's see how this runs on travis.

Fixes https://github.com/datproject/dat-desktop/issues/310

Labeled as `Priority: High` as lack of QA is an issue for us.

### CODE REVIEW

**Comment by juliangruber** [comment]
passes on osx but fails on linux

**Comment by juliangruber** [comment]
but should be fixable :)

**Comment by juliangruber** [comment]
passes!

**Comment by karissa** [comment]
nice! merge away

**Comment by juliangruber** [comment]
aw yiss!

**Pull request merged**
