### PR TITLE
contributing: add pull request time frame

### PR DESCRIPTION
**Pull request by juliangruber**

### CODE REVIEW

**Comment by juliangruber** [comment]
This is the other way around: If a main contributor creates a pull request and doesn't receive review in this time frame, it should be good to merge. A pull request from a non main contributor should never be merged without prior review from a main contributor.

**Comment by juliangruber** [comment]
Maybe you had a different goal then?

**Comment by juliangruber** [comment]
what I wrote applies to both external and internal contributors:

- for an external contributor it means not to worry if their PR doesn't receive any attention for 36h
- for an internal contributor it means to wait for 36h before deciding there won't be more reviews and then deciding on whether to merge or not

**Comment by martinheidegger** [comment]
You are right: there are two goals. What I was focussing on was two things:

1. Weekends. People need to know that other people rest ^_^
2. To Avoid confusion if a PR is merged as is without a comment.

of course your goal would be completely lost in my suggestion 😞

**Comment by juliangruber** [comment]
how about this? :)

**Pull request merged**
